### ISSUE TITLE
The docker image on Docker Hub for version 1.2.7 (latest) has broken auto language detect

### ISSUE THREAD

**Issue by MatsBjerin** [LibreTranslate/LibreTranslate#217]
To replicate

1. Create this docker-compose file:

```
version: "3"

services:
  libretranslate:
    image: libretranslate/libretranslate:latest
    container_name: libretranslate
    stdin_open: true
    tty: true
    restart: unless-stopped
    ports:
      - 5000:5000
```

2. Start with: "docker-compose up -d"

3. Then run this:
`curl -X POST -H "Content-Type: application/json" -d '{"q": "Ciao!", "source": "auto", "target": "en"}' localhost:5000/translate`

The language auto detect will fail and no translation is made.
