### ISSUE TITLE
Unable to download models when using docker

### ISSUE THREAD

**Issue by alpap** [LibreTranslate/LibreTranslate#332]
Found 56 models
Downloading Arabic → English (1.0) ...
(URLError(ConnectionRefusedError(111, 'Connection refused')),)
(URLError(ConnectionRefusedError(111, 'Connection refused')),)
(URLError(ConnectionRefusedError(111, 'Connection refused')),)

**Comment by pierotofy** [comment]
Hey @alpap :wave: are you connected directly through the internet or via VPN? It looks like a network configuration error or a firewall issue, not a bug in LibreTranslate per-se.

**Comment by Alumniminium** [comment]
I'm having the same issue. In my case its error 110

(URLError(TimeoutError(110, 'Connection timed out')),)
(URLError(TimeoutError(110, 'Connection timed out')),)

**Comment by grigio** [comment]
I'm having the same issue with this `docker-compose.yml`

```
version: "3"

services:
  libretranslate:
    container_name: libretranslate
    image: libretranslate/libretranslate
    restart: unless-stopped
    ports:

```
