### ISSUE TITLE
PermissionError: [Errno 13] Permission denied

### ISSUE THREAD

**Issue by Joly0** [LibreTranslate/LibreTranslate#378]
Hey, i just tried to set this up and i keep getting these error messages:

> Traceback (most recent call last):
  File "./venv/bin/libretranslate", line 33, in <module>
    sys.exit(load_entry_point('libretranslate==1.3.8', 'console_scripts', 'libretranslate')())
  File "./venv/bin/libretranslate", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/local/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/venv/lib/python3.8/site-packages/libretranslate/__init__.py", line 2, in <module>
    from .main import main
  File "/app/venv/lib/python3.8/site-packages/libretranslate/main.py", line 5, in <module>
    from libretranslate.app import create_app
  File "/app/venv/lib/python3.8/site-packages/libretranslate/app.py", line 9, in <module>
    import argostranslatefiles
  File "/app/venv/lib/python3.8/site-packages/argostranslatefiles/__init__.py", line 1, in <module>
    from argostranslatefiles.argostranslatefiles import *
  File "/app/venv/lib/python3.8/site-packages/argostranslatefiles/argostranslatefiles.py", line 1, in <module>
    from argostranslate.translate import ITranslation
  File "/app/venv/lib/python3.8/site-packages/argostranslate/translate.py", line 8, in <module>
    from argostranslate import package, settings, sbd, apis, fewshot
  File "/app/venv/lib/python3.8/site-packages/argostranslate/package.py", line 11, in <module>
    from argostranslate import networking
  File "/app/venv/lib/python3.8/site-packages/argostranslate/networking.py", line 6, in <module>
    from argostranslate.utils import info, error
  File "/app/venv/lib/python3.8/site-packages/argostranslate/utils.py", line 4, in <module>
    from argostranslate import settings
  File "/app/venv/lib/python3.8/site-packages/argostranslate/settings.py", line 22, in <module>
    os.makedirs(data_dir, exist_ok=True)
  File "/usr/local/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/home/libretranslate/.local/share/argos-translate'

**Comment by pierotofy** [comment]
How are you running the app? Operating system?

**Comment by Joly0** [comment]
> How are you running the app? Operating system?

Unraid 6.11.5

**Comment by dingedi** [comment]
does the user running the command have the necessary permissions?

**Comment by Joly0** [comment]
What command?
I just updated the docker container and it seems like the issue resolved itself. Atleast container loads without a problem, webui is accessible and all the languages are there.

**Comment by janaxhell** [comment]
Just tried to deploy on Docker and got exactly the same error. I've tried to tinker adding PUID/PGID variables, but the error won't go away. Restarted several times and it did not make any difference. 
My compose:

```
version: '3.8'
services:
    libretranslate:
      container_name: libretranslate
      image: libretranslate/libretranslate
      tty: true
      stdin_open: true
      ports:
        - 5000:5000
## Uncomment this section and the libretranslate_api_keys volume if you want to backup your API keys

      environment:
        - LT_API_KEYS=true
        - LT_API_KEYS_DB_PATH=/app/db/api_keys.db # Same result as `db/api_keys.db` or `./db/api_keys.db`
        - PUID=998
        - PGID=100
        
## Uncomment these vars and libretranslate_models volume to optimize loading time.

        - LT_UPDATE_MODELS=true
        - LT_LOAD_ONLY=it,jp,en
      volumes:
        - /srv/dev-disk-by-uuid-8998116d-e145-4319-8c9f-41609747f657/Configs/libretranslate/data:/home/libretranslate/.local/share
        - /srv/dev-disk-by-uuid-8998116d-e145-4319-8c9f-41609747f657/Configs/libretranslate/cache:/home/libretranslate/.local/cache
        - /srv/dev-disk-by-uuid-8998116d-e145-4319-8c9f-41609747f657/Configs/libretranslate/libretranslate_api_keys:/app/db
        
# Keep the models in a docker volume, to avoid re-downloading on startup

        - /srv/dev-disk-by-uuid-8998116d-e145-4319-8c9f-41609747f657/Configs/libretranslate/libretranslate_models:/home/libretranslate/.local:rw
  
networks:
  default:
    external:
      name: omv2
```
