### ISSUE TITLE
broken offline mode

### ISSUE THREAD

**Issue by Dominion0815** [LibreTranslate/LibreTranslate#47]
If I try --offline in docker-compose command line, then I will get this error message in container log:

```
libretranslate_1  | Traceback (most recent call last):
libretranslate_1  |   File "/usr/local/bin/libretranslate", line 8, in <module>
libretranslate_1  |     sys.exit(main())
libretranslate_1  |   File "/usr/local/lib/python3.8/site-packages/app/main.py", line 35, in main
libretranslate_1  |     app = create_app(args)
libretranslate_1  |   File "/usr/local/lib/python3.8/site-packages/app/app.py", line 75, in create_app
libretranslate_1  |     raise AttributeError(f"{args.frontend_language_source} as frontend source language is not supported.")
libretranslate_1  | AttributeError: en as frontend source language is not supported.
libretranslate_1  | Traceback (most recent call last):
libretranslate_1  |   File "/usr/local/bin/libretranslate", line 8, in <module>
libretranslate_1  |     sys.exit(main())
libretranslate_1  |   File "/usr/local/lib/python3.8/site-packages/app/main.py", line 35, in main
libretranslate_1  |     app = create_app(args)
libretranslate_1  |   File "/usr/local/lib/python3.8/site-packages/app/app.py", line 75, in create_app
libretranslate_1  |     raise AttributeError(f"{args.frontend_language_source} as frontend source language is not supported.")
libretranslate_1  | AttributeError: en as frontend source language is not supported.
```

my docker-compose.yml file:

```
docker-compose.yml
version: "3"

services:
  libretranslate:
    build: .
    restart: unless-stopped
    ports:
      - 127.0.0.1:5000:5000
    command: --offline
```

I also get this error message with this command line:

`command: --req-limit 100 --char-limit 3000 --host 0.0.0.0 --port 5000 --frontend-language-source en --frontend-language-target de --frontend-timeout 500 --offline`

**Comment by pierotofy** [comment]
Thanks for the report! It works without `--offline` though?

**Comment by Dominion0815** [comment]
yes

**Comment by ErQrYfkrju** [comment]
There are two issues with offline mode:
1. setup.py does not include static resources and this issues should be resolved using [pull request](https://github.com/uav4geo/LibreTranslate/pull/45)
2. the other one, is that before using offline mode, you should download and cache models (--without offline flag), here is my docker-compose
```
version: "3"

services:
  libretranslate:
    container_name: libretranslate
    build: .
    restart: unless-stopped
    volumes:
      - /tmp/argos-translate:/root/.local/share/argos-translate
    ports:
      - 5000:5000
    ## Uncomment above command and define your args if necessary
    command: --req-limit 100 --offline
```
    btw it won`t start if there is not --req-limit param
