### ISSUE TITLE
Translations on M1 crash docker container 

### ISSUE THREAD

**Issue by caudurodev** [LibreTranslate/LibreTranslate#524]
I have pulled the latest docker images:

- libretranslate/libretranslate:latest
- libretranslate/libretranslate:v1.4
- libretranslate/libretranslate:v1.3.13

All have an issue which cause an internal error when attempting any translation that is not en->en. The issue occurs both on the web interface and via the API. There is no relevant logging info even when `LT_DEBUG=1` flag is enabled.

Downloading currently `LT_LOAD_ONLY=en,de` models and can verify the files are present in 
```
/home/libretranslate/.local/share/argos-translate/packages/
```

Accessing the url `http://localhost:5000/?source=de&target=en&q=H`

results in:
```
libretranslate exited with code 139
libretranslate  | Updating language models
libretranslate  | Found 86 models
libretranslate  | Keep 2 models
libretranslate  | Loaded support for 2 languages (2 models total)!
libretranslate  |  * Serving Flask app 'libretranslate.app'
libretranslate  |  * Debug mode: off
libretranslate  | WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
libretranslate  |  * Running on all addresses (0.0.0.0)
libretranslate  |  * Running on http://127.0.0.1:5000
libretranslate  |  * Running on http://172.28.0.2:5000
libretranslate  | Press CTRL+C to quit
```

![image](https://github.com/LibreTranslate/LibreTranslate/assets/60057887/e9a910ff-4638-45db-a2db-b206e39a7cf9)

I'm using docker-compose.yml:
```
version: "3"

services:
  libretranslate:
    container_name: libretranslate
    image: libretranslate/libretranslate:latest
    ports:
    - "5000:5000"
    restart: unless-stopped
    environment:
      - LT_UPDATE_MODELS=1
      - LT_DEBUG=1
      - LT_LOAD_ONLY=en,de
```

My env:

Mac M2, using docker desktop 4.24.2 (124339) (Docker engine  24.0.6)
