### ISSUE TITLE
(URlError(gaierror(-3, 'Temporary failure in name resolution')),) 

### ISSUE THREAD

**Issue by tjuzdy** [LibreTranslate/LibreTranslate#609]
my docker-compose.yml like this
```
version: "3"

services:
  libretranslate:
    image: libretranslate/libretranslate:latest
    container_name: libretranslate
    restart: unless-stopped
    ports:
      - "5000:5000"
    healthcheck:
      test: ['CMD-SHELL', './venv/bin/python scripts/healthcheck.py']     
    volumes:
      - /opt/libretranslate_models:/home/libretranslate/.local:rw
```
then i manually download all language packs in /opt/libretranslate_models
when i run docker-compose up -d， it always Updating language models

and then it does not works
