### ISSUE TITLE
Issue with docker-compose

### ISSUE THREAD

**Issue by ThomasBossuat** [LibreTranslate/LibreTranslate#63]
Hey,

Thanks for the good job ! But I have an issue with dockeer-compose, indeed when I use `docker-compose up -d --build` the container launches perfectly : 

![alt text](https://i.postimg.cc/zfzp7ZBx/tmp.png) 

but when I go to http://localhost:5000 there is nothing.
However, with `docker run -ti --rm -p 5000:5000 libretranslate/libretranslate` it works.
I would like to know if I made something wrong knowing that I have the latest version. Docker-compose is very important for my deployment configuration.

Thank you in advance !

**Comment by FranciscoMendes10866** [comment]
In my case, it doesn't work either way. It doesn't matter if I clone the repository and build the image. It doesn't matter if I use the docker run or if I use the image available on the docker hub.

It is the only technology that is not working properly on my pc.

**Comment by worldworm** [comment]
I'am using the docker-compose file with the official docker hub image. Works great!

@FranciscoMendes10866 Just replace "build: ." with "image: libretranslate/libretranslate:latest"

**Comment by FranciscoMendes10866** [comment]
> I'am using the docker-compose file with the official docker hub image. Works great!
> 
> @FranciscoMendes10866

Can you share which command you used or how you structured the docker compose?

Because on my computer it still doesn't work 😢

**Comment by worldworm** [comment]
I'am ruinning it using traefik as a reverse proxy, so my setup is a bit different.
But I tried it using the default docker-compose from the repo and just replaced `build: .` with `image: libretranslate/libretranslate:latest`

```
version: "3"

services:
  libretranslate:
    container_name: libretranslate
    image: libretranslate/libretranslate:latest
    restart: unless-stopped
    ports:
      - 5000:5000
```

**Important**: Give the container a few minutes to startup. It is downloading the translation packages at first startup (I think).

**Comment by euberdeveloper** [comment]
I had the same problem, it took a lot of time to download the models. I used the env "LOAD_ONLY=it,en" because I needed to download only those two languages. It took less time and disk space and it worked.

However, on portainer, I cannot see the log of the downloading process. If I click "logs", I see an empty content.

**Comment by BenB196** [comment]
So I think the issue with the logs not showing up, is that the app doesn't properly send logs to stdin and stderr, though I could be wrong here.

**Comment by pierotofy** [comment]
Closing as this seems related to docker, not necessarily a bug in LT. Feel free to re-open if this is not the case. :pray:

**Comment by CodeStarrk** [comment]
I don't understand how you guys got this to work, I have done the exact same things, with the latest image, waited 10 minutes and I still get a ''socket hang up'' whenever I do a post request on port 5000, but whenever I do `docker run -ti --rm -p 5000:5000 libretranslate/libretranslate ` it just works. The logs in docker compose are empty, and after like 5 minutes of running the container I get a `libretranslate         | (<HTTPError 503: 'Service Unavailable'>,)`

**Comment by worldworm** [comment]
Hey @CodeStarrk 
for whatever reason the log does not show up when using docker compose. I tried setting `tty: true` and that worked for me. To speed up the download try setting `LT_LOAD_ONLY`.

I've tested with that:
```yml
version: "3"

services:
  libretranslate:
    container_name: libretranslate
    image: libretranslate/libretranslate:latest
    restart: unless-stopped
    ports:
      - "5000:5000"
    healthcheck:
      test: ['CMD-SHELL', './venv/bin/python scripts/healthcheck.py']
    tty: true
    environment:
      LT_LOAD_ONLY: en,de
```

![grafik](https://github.com/LibreTranslate/LibreTranslate/assets/13227454/249915a2-9e71-4f03-a142-be89f7ce069c)
