### ISSUE TITLE
502 Bad Gateway on Nginx with Docker

### ISSUE THREAD

**Issue by nehemiagurl** [LibreTranslate/LibreTranslate#724]
we have libretranslate (https://khir.tooot.im) running with docker-compose. the `docker-compose.yml` has the following:
```
  libretranslate:
    image: libretranslate/libretranslate:latest
      #    ports:
      #      - 5000:5000 # Should be 5000: to isolate the service to docker, right?
      #      - 5000 # Should be 5000: to isolate the service to docker, right?
    expose:
      - "5000"
      #    command: --char-limit 5000 --req-limit 120 --frontend-language-target he --api-keys --get-api-key-link "https://tooot.im/@admin" --update-models
    volumes:
      - ./ltdata:/app/ltdata:rw
    command: --host 0.0.0.0 --char-limit 5000 --req-limit 120 --frontend-language-target he --api-keys --api-keys-db-path /app/ltdata/api_keys.db --get-api-key-link "https://tooot.im/@admin" --update-models
    restart: unless-stopped
```
this hasn't changed in a while and there's been several updates and `docker-compose up -d` with this config with no problem.
several updates ago the instance stopped responding. i assumed this was due to a bad update (this happened in the past and was resolved by updating again), but this time updating further did not help.
libretranslate doesn't seem to dump anything to `docker logs` so i fully do not know what caused the problem, which obviously makes it way harder to debug.
