### ISSUE TITLE
Error pulling libretranslate-libretranslate-cuda:latest - Repository does not exist or access denied

### ISSUE THREAD

**Issue by Marioalf2002** [LibreTranslate/LibreTranslate#756]
### **Description**:

I encountered an issue while trying to pull the Docker image `libretranslate-libretranslate-cuda:latest`. The error message I received is as follows:

Error response from daemon: pull access denied for libretranslate-libretranslate-cuda, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

#### **Steps to Reproduce**:

1. Run the following command to pull the image:
   ```bash
   docker pull libretranslate-libretranslate-cuda:latest
   ```
2. Observe the error message.

#### **Expected Behavior**:
The image `libretranslate-libretranslate-cuda:latest` should be successfully pulled from the repository.

#### **Actual Behavior**:
The command fails with the error:
```
Error response from daemon: pull access denied for libretranslate-libretranslate-cuda, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```

#### **Possible Causes**:
1. The repository `libretranslate-libretranslate-cuda` does not exist in Docker Hub.
2. The repository exists but is private, and the required credentials are not provided or insufficient.
3. There might be a typo or incorrect naming of the image.

### **Question**:
If this image (`libretranslate-libretranslate-cuda:latest`) is intended to be updated regularly, how should users pull the latest updates? For example:
- Should we use `docker pull libretranslate-libretranslate-cuda:latest` to get updates?
- If the repository is private, what are the steps to authenticate and ensure we can pull updates?
- Are there alternative images or methods recommended for updating LibreTranslate with CUDA support?

#### **Additional Information**:
- Docker version: `28.0.0`
- Operating System: `Arch Linux`
- Command used: `docker pull libretranslate-libretranslate-cuda:latest`

Thank you for your attention to this issue!

**Comment by Marioalf2002** [comment]
> The correct image is `libretranslate/libretranslate:latest-cuda` ?

That is what I want to know well, since the docker-compose.cuda.yml created the image with the name `libretranslate-libretranslate-cuda latest 18d18dcacd66 2 days ago 16.6GB`

```
version: "3"

services:
  libretranslate-cuda:
    container_name: libretranslate-cuda
    build:
      context: .
      dockerfile: docker/cuda.Dockerfile
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - LT_API_KEYS=true
      - LT_API_KEYS_DB_PATH=/app/db/api_keys.db
      - LT_UPDATE_MODELS=true
    volumes:
      - libretranslate_api_keys:/app/db
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

volumes:
  libretranslate_api_keys:
```
