### ISSUE TITLE
Automatic permissions for bind mount volume in docker compose.

### ISSUE THREAD

**Issue by 0fflineuser** [LibreTranslate/LibreTranslate#772]
HI, 
I just wanted to document how to set the proper permissions automatically when using a bind mount as this is what I use.
We need to use [post_start](https://docs.docker.com/compose/how-tos/lifecycle/#post-start-hooks).
Here is my docker-compose.yml file, hope this help someone.

```
services:
  libretranslate:
    container_name: libretranslate
    hostname: libretranslate
    image: libretranslate/libretranslate
    restart: unless-stopped
    ports:
      - "5000:5000"
    tty: true
    healthcheck:
      test: ['CMD-SHELL', './venv/bin/python scripts/healthcheck.py']
    environment:
      - LT_API_KEYS=true
      - LT_API_KEYS_DB_PATH=/app/db/api_keys.db
      - LT_UPDATE_MODELS=true
      - LT_LOAD_ONLY=de,en,es,fr,ja,ko,pt,ru,zt,zh # See https://libretranslate.com/languages
    volumes:
      - "./storage-libretranslate/api_keys/:/app/db"
      - "./storage-libretranslate/models/:/home/libretranslate/.local:rw"
    post_start:
      - command: ["sh", "-c", "chown 1032 /home/libretranslate/.local/ && chown 1032 /app/db"]
        user: root
```
